/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parques;

import java.awt.Color;
import java.awt.Graphics;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author johan
 */
public class Parques1 extends javax.swing.JPanel implements Runnable{
 int recorrido=0;
 int jugador=1;
 
 int x=90,y=90,x1=90,y1=110;
 int posX=0,posY=0,posX1=0,posY1=0,mover=0;
 int dado11,dado21;
 
 int [] posX7={250,120,430,560};
 int [] posY7={130,440,560,250};
 int [] posX5={120,10,270,330,560,670,430,350};
 int [] posY5={260,350,560,670,440,340,130,18};
 int []posicionesX={270,120,10,120,260,340,430,560,670,560,420,340};
 int []posicionesY={130,260,350,440,560,670,560,420,340,250,130,18};
 int [] posicionSX={0,250,560,440,260};
  int [] posicionSY={0,130,230,560,560};
 
         
 Thread hilo1,hilo2;
    /**
     * Creates new form Parques1
     */
    public Parques1() {
       
        initComponents();
        
        
                         
    }
    public void paint(Graphics sd){
        super.paint(sd);
        ficha1.setLocation(x, y);
        ficha2.setLocation(x1, y1);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ficha4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ficha3 = new javax.swing.JLabel();
        ficha2 = new javax.swing.JLabel();
        ficha1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lanzar = new javax.swing.JButton();
        dado1 = new javax.swing.JLabel();
        dado2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        ficha4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bola2.jpg"))); // NOI18N
        add(ficha4);
        ficha4.setBounds(560, 130, 18, 16);

        jLabel5.setText("jLabel5");
        add(jLabel5);
        jLabel5.setBounds(260, 560, 10, 14);

        ficha3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bola2.jpg"))); // NOI18N
        add(ficha3);
        ficha3.setBounds(560, 100, 18, 16);

        ficha2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/circulo1.png"))); // NOI18N
        ficha2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ficha2MouseClicked(evt);
            }
        });
        add(ficha2);
        ficha2.setBounds(90, 110, 40, 16);

        ficha1.setBackground(new java.awt.Color(0, 0, 102));
        ficha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/circulo1.png"))); // NOI18N
        ficha1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ficha1MouseClicked(evt);
            }
        });
        add(ficha1);
        ficha1.setBounds(90, 80, 50, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/parque12.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 700);

        lanzar.setBackground(new java.awt.Color(0, 102, 102));
        lanzar.setForeground(new java.awt.Color(255, 255, 255));
        lanzar.setText("LANZAR");
        lanzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanzarActionPerformed(evt);
            }
        });
        add(lanzar);
        lanzar.setBounds(770, 130, 100, 30);

        dado1.setText("jLabel5");
        add(dado1);
        dado1.setBounds(730, 200, 70, 80);

        dado2.setText("jLabel6");
        add(dado2);
        dado2.setBounds(840, 200, 70, 80);

        jLabel4.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DE DADOS");
        add(jLabel4);
        jLabel4.setBounds(770, 70, 160, 50);

        jLabel3.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LANZAMIENTO");
        add(jLabel3);
        jLabel3.setBounds(750, 30, 160, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(-45, -3, 1050, 790);
    }// </editor-fold>//GEN-END:initComponents

    private void lanzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanzarActionPerformed
      switch(jugador){
          case 1:{
              lanzarDados(1);
              break;
          }
          case 2:{
              lanzarDados(2);
              break; 
          }
          
      }
     
    }//GEN-LAST:event_lanzarActionPerformed

    private void ficha2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ficha2MouseClicked
     System.out.println("AQUI ESToy desd hace arto "+mover);
      if(mover==7){
      moverficha(2,7);
      }
      if(mover==5){
          System.out.println("AQUI ESTOY 5$$$$");
            moverficha(2,5);
      }
    }//GEN-LAST:event_ficha2MouseClicked

    private void ficha1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ficha1MouseClicked
      System.out.println("AQUI ESToy desd hace arto "+mover); 
     if(mover==7){
      moverficha(1,7);
      }
      if(mover==5){
          System.out.println("AQUI ESTOY 5.....");
            moverficha(1,5);
      }
    }//GEN-LAST:event_ficha1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dado1;
    private javax.swing.JLabel dado2;
    private javax.swing.JLabel ficha1;
    private javax.swing.JLabel ficha2;
    private javax.swing.JLabel ficha3;
    private javax.swing.JLabel ficha4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton lanzar;
    // End of variables declaration//GEN-END:variables

    private void movimientos(int dado1,int dado2,int jugador) {
       
       int movimientos=0;
       int movficha1=0,movficha2=0;
        
        ficha1.setEnabled(false);
        ficha2.setEnabled(false);
        
        if(dado1==dado2){
            if(jugador==1){
            ficha1.setEnabled(true);
            ficha2.setEnabled(true);
                System.out.println("AQUI ESTOY CUANDO ES PAR");
           if(hilo1!=null){
               
               hilo1=new Thread(this);
               hilo1.start();
               
               
           }
           else{
                hilo1=new Thread(this);
                hilo1.start();
           }
           jugador=2;
            }
            else{
                if(jugador==2){
                    ficha3.setEnabled(true);
                    ficha4.setEnabled(true); 
                        System.out.println("AQUI ESTOY CUANDO ES PAR");
                        if(hilo1!=null){

                            hilo1=new Thread(this);
                            hilo1.start();


                        }
                        else{
                             hilo1=new Thread(this);
                             hilo1.start();
                        }
                             }
                        jugador=1;
                         }
            //recorrido++;
            System.out.println("AQUI ESTOY CUANDO ES PAR");
           
           
        }
        if((dado1+dado2)==7){
            movimientos=0;
            movficha1=0;
            movficha2=0;
            for(int i=0;i<posX7.length;i++){
                   //System.out.println("ENTRO AQUI 1"+posX7[i]+"--"+ficha1.getX()+ficha2.getX()+"--"+ficha1.getY()+"--"+ficha2.getY());
                if((ficha1.getX()<=(posX7[i]+20) && ficha1.getX()>=(posX7[i]-20)) && (ficha1.getY()<=(posY7[i]+20) && ficha1.getY()>=(posY7[i]-20))  ){
                    movficha1++;
                    movimientos++;
                 }
                 if((ficha2.getX()<=(posX7[i]+20)&&ficha2.getX()>=(posX7[i]-20)) && (ficha2.getY()<=(posY7[i]+20) && ficha2.getY()>=(posY7[i]-20))  ){
                        movficha2++;
                        movimientos++;
                   
                }
            }
              if(movimientos>=2){
                    mover=7;
                    System.out.println("ENTRO AQUI CUANDO ESTAN EN LA MISMA POSICION");
                    ficha1.setEnabled(true);
                     ficha2.setEnabled(true); 
                    JOptionPane.showMessageDialog(this, "Seleccione la ficha a mover", "Error", JOptionPane.ERROR_MESSAGE);
              }else{
                  if(movficha1==1){
                      moverficha(1,7);
                  }else{
                      if(movficha2==1){
                          moverficha(2,7);
                      }
                  }
              }
              
            
            }
        if((dado1+dado2)==5 || dado1==5 || dado2==5){
            movficha1=0;
            movficha2=0;
            movimientos=0;
            for(int i=0;i<posX5.length;i++){
                 //  System.out.println("ENTRO AQUI 1"+posX5[i]+"--"+ficha1.getX()+ficha2.getX()+"--"+ficha1.getY()+"--"+ficha2.getY());
                if((ficha1.getX()<=(posX5[i]+20) && ficha1.getX()>=(posX5[i]-20)) && (ficha1.getY()<=(posY5[i]+20) && ficha1.getY()>=(posY5[i]-20))  ){
                     System.out.println("AQUI ESTOY 151111");
                    movficha1++;
                    movimientos++;
                 }
                 if((ficha2.getX()<=(posX5[i]+20)&&ficha2.getX()>=(posX5[i]-20)) && (ficha2.getY()<=(posY5[i]+20) && ficha2.getY()>=(posY5[i]-20))  ){
                         System.out.println("AQUI ESTOY 161111");
                        movficha2++;
                        movimientos++;
                   
                }
            }
              if(movimientos>=2){
                    mover=5;
                     System.out.println("AQUI ESTOY 171111 "+movimientos);
                    ficha1.setEnabled(true);
                     ficha2.setEnabled(true); 
                    JOptionPane.showMessageDialog(this, "Seleccione la ficha a mover", "Error", JOptionPane.ERROR_MESSAGE);
              }else{
                  if(movficha1==1){
                       System.out.println("AQUI ESTOY 181111 " +movficha1);
                      moverficha(1,5);
                  }else{
                      if(movficha2==1){
                           System.out.println("AQUI ESTOY 191111 "+movficha2);
                          moverficha(2,5);
                      }
                  }
              }
        }
      
    }

    @Override
    public void run() {
        int bandera=0,posicion=0;
        try{
          if((ficha1.getX()>5&&ficha1.getX()<205)&&(ficha1.getY()>5&&ficha1.getY()<205) ){
              posicion=1;
          }else{
              if((ficha3.getX()>430 &&ficha1.getX()<660)&&(ficha3.getY()>5&&ficha1.getY()<205) ){
                posicion=2;
          }
          }
           while(x<=posicionSX[1] || y<=posicionSY[1]){
               if(x<=posX){
               Thread.sleep(90);
               x+=10;
               repaint();
               }
               if(y<=posY){
                    Thread.sleep(90);
                    y+=10;
                    repaint();
               }
           }
           while((x1<=(posicionSX[1]+15))|| (y<=(posicionSY[1]+15))){
               if(x1<=260){
               Thread.sleep(90);
               x1+=10;
               repaint();
               }
               if(y1<=120){
                    Thread.sleep(90);
                    y1+=10;
                    repaint();
               }
           }
        
        } catch (InterruptedException ex) {
         Logger.getLogger(Parques1.class.getName()).log(Level.SEVERE, null, ex);
        
        }
}

    private void moverficha(int ficha,int mover) {
        int j=0;
       switch(mover){
           case 7:{ 
       
        switch(ficha){
            case 1:{
              for( j=0;j<posicionesX.length;j++){
                if((ficha1.getX()<=(posicionesX[j]+20) && ficha1.getX()>=(posicionesX[j]-20)) && (ficha1.getY()<=(posicionesY[j]+20) && ficha1.getY()>=(posicionesY[j]-20))  ){  
                  for(int i=0;i<posX7.length;i++){
                  //  System.out.println(ficha2.getX()+"--"+posicionesX[i]+"---"+posicionesY[i]+"--"+ficha2.getY());
                   if((ficha1.getX()<=(posX7[i]+20) && ficha1.getX()>=(posX7[i]-20)) && (ficha1.getY()<=(posY7[i]+20) && ficha1.getY()>=(posY7[i]-20))  ){
                       System.out.println("AQUI ESTOY 12");
                       if(i==0||i==2){
                           System.out.println("AQUI ESTOY 13");
                        if(ficha2.getY()<=(posicionesY[j+1]+20) && ficha2.getY()>=(posicionesY[j+1]-20)){
                            System.out.println("AQUI ESTOY 14");
                            x=posicionesX[j+1];
                            y=(posicionesY[j+1]+15);
                            ficha1.setLocation(x, y);
                             System.out.println(ficha1.getX()+"--"+ficha1.getY());
                            j++;
                            break;
                        }else{
                            System.out.println("AQUI ESTOY 15");
                            x=posicionesX[j+1];
                            y=(posicionesY[j+1]);
                            ficha1.setLocation(x, y);
                             System.out.println(ficha1.getX()+"--"+ficha1.getY());
                            j++;
                              break;
                     }
                    }
                     else{
                           if(ficha2.getX()<=(posicionesX[j+1]+20) && ficha2.getX()>=(posicionesX[j+1]-20)){
                            System.out.println("AQUI ESTOY 16");
                            x=(posicionesX[j+1]+15);
                            y=posicionesY[j+1];
                            ficha1.setLocation(x, y);
                             System.out.println(ficha1.getX()+"--"+ficha1.getY());
                            j++;
                            break;
                        }else{
                            System.out.println("AQUI ESTOY 17");
                            x=posicionesX[j+1];
                            y=(posicionesY[j+1]);
                            ficha1.setLocation(x, y);
                             System.out.println(ficha1.getX()+"--"+ficha1.getY());
                            j++;
                            break;
                            
                     }
                     }
                  }
                }
                }
              }
                break;  
            }
          case 2:{
            for(j=0;j<posicionesX.length;j++){
              if((ficha2.getX()<=(posicionesX[j]+20) && ficha2.getX()>=(posicionesX[j]-20)) && (ficha2.getY()<=(posicionesY[j]+20) && ficha2.getY()>=(posicionesY[j]-20))  ){  
              
                for(int i=0;i<posX7.length;i++){
                   // System.out.println(ficha2.getX()+"--"+posicionesX[i]+"---"+posicionesY[i]+"--"+ficha2.getY());
                   if((ficha2.getX()<=(posX7[i]+20) && ficha2.getX()>=(posX7[i]-20)) && (ficha2.getY()<=(posY7[i]+20) && ficha2.getY()>=(posY7[i]-20))  ){
                       System.out.println("AQUI ESTOY 12--");
                       if(i==0||i==2){
                           System.out.println("AQUI ESTOY 13");
                        if(ficha1.getY()<=(posicionesY[j+1]+20) && ficha1.getY()>=(posicionesY[j+1]-20)){
                            System.out.println("AQUI ESTOY 14--");
                            x1=posicionesX[j+1];
                            y1=(posicionesY[j+1]+15);
                            ficha2.setLocation(x1, y1);
                             System.out.println(ficha2.getX()+"--"+ficha2.getY());
                            j++;
                            break;
                        }else{
                            System.out.println("AQUI ESTOY 15--");
                            x1=posicionesX[j+1];
                            y1=(posicionesY[j+1]);
                            ficha2.setLocation(x1, y1);
                             System.out.println(ficha2.getX()+"--"+ficha2.getY());
                            j++;
                              break;
                     }
                    }
                     else{
                            if(ficha1.getX()<=(posicionesX[j+1]+20) && ficha2.getX()>=(posicionesX[j+1]-20)){
                            System.out.println("AQUI ESTOY 16--");
                            x1=(posicionesX[j+1]+15);
                            y1=posicionesY[j+1];
                            ficha2.setLocation(x1, y1);
                            System.out.println(ficha2.getX()+"--"+ficha2.getY());
                            j++;
                            break;
                        }else{
                            System.out.println("AQUI ESTOY 17--");
                            x1=posicionesX[j+1];
                            y1=(posicionesY[j+1]);
                            ficha2.setLocation(x1, y1);
                             System.out.println(ficha2.getX()+"--"+ficha2.getY());
                            j++;
                            break;
                            
                     }
                     }
                  }
                }
                
               break; 
            }
        }}}
           break;
           } 
           case 5:{
               System.out.println("ENTRE A FICHA 5-----------------");
             switch(ficha){
               case 1:{
                 for(j=0;j<posicionesX.length;j++){
                        if((ficha1.getX()<=(posicionesX[j]+20) && ficha1.getX()>=(posicionesX[j]-20)) && (ficha1.getY()<=(posicionesY[j]+20) && ficha1.getY()>=(posicionesY[j]-20))  ){  
                          for(int i=0;i<posX5.length;i++){
                          
                           if((ficha1.getX()<=(posX5[i]+20) && ficha1.getX()>=(posX5[i]-20)) && (ficha1.getY()<=(posY5[i]+20) && ficha1.getY()>=(posY5[i]-20))  ){
                               System.out.println("AQUI ESTOY 121");
                               if(i==0||i==1 || i==4 || i==5){
                                   System.out.println("AQUI ESTOY 131");
                                if(ficha2.getY()<=(posicionesY[j+1]+20) && ficha2.getY()>=(posicionesY[j+1]-20)){
                                    System.out.println("AQUI ESTOY 141");
                                    x=posicionesX[j+1];
                                    y=(posicionesY[j+1]+15);
                                    ficha1.setLocation(x, y);
                                    j++;
                                    System.out.println(ficha1.getX()+"--"+ficha1.getY());
                                    break;
                                }else{
                                    System.out.println("AQUI ESTOY 151");
                                    x=posicionesX[j+1];
                                    y=(posicionesY[j+1]);
                                    ficha1.setLocation(x, y);
                                     j++;
                                     System.out.println(ficha1.getX()+"--"+ficha1.getY());
                                      break;
                             }
                            }
                             else{
                                   if(ficha2.getX()<=(posicionesX[j+1]+20) && ficha2.getX()>=(posicionesX[j+1]-20)){
                                    System.out.println("AQUI ESTOY 161");
                                    x=(posicionesX[j+1]+15);
                                    y=posicionesY[j+1];
                                    ficha1.setLocation(x, y);
                                     j++;
                                     System.out.println(ficha1.getX()+"--"+ficha1.getY());
                                    break;
                                }else{
                                    System.out.println("AQUI ESTOY 171");
                                    x=posicionesX[j+1];
                                    y=(posicionesY[j+1]);
                                    ficha1.setLocation(x, y);
                                     j++;
                                     System.out.println(ficha1.getX()+"--"+ficha1.getY());
                                    break;

                             }
                             }
                          }
                        }
                        }}
                        break;  
                    }
                 case 2:{
                    for(j=0;j<posicionesX.length;j++){
                      if((ficha2.getX()<=(posicionesX[j]+20) && ficha2.getX()>=(posicionesX[j]-20)) && (ficha2.getY()<=(posicionesY[j]+20) && ficha2.getY()>=(posicionesY[j]-20))  ){  
                        for(int i=0;i<posX5.length;i++){
                            //System.out.println(ficha2.getX()+"--"+posicionesX[i]+"---"+posicionesY[i]+"--"+ficha2.getY());
                           if((ficha2.getX()<=(posX5[i]+20) && ficha2.getX()>=(posX5[i]-20)) && (ficha2.getY()<=(posY5[i]+20) && ficha2.getY()>=(posY5[i]-20))  ){
                               System.out.println("AQUI ESTOY 122");
                               if(i==0||i==2){
                                   System.out.println("AQUI ESTOY 132");
                                if(ficha1.getY()<=(posicionesY[j+1]+20) && ficha2.getY()>=(posicionesY[j+1]-20)){
                                    System.out.println("AQUI ESTOY 142");
                                    x1=posicionesX[j+1];
                                    y1=(posicionesY[j+1]+15);
                                    ficha2.setLocation(x1, y1);
                                     j++;
                                     System.out.println(ficha2.getX()+"--"+ficha2.getY());
                                    break;
                                }else{
                                    System.out.println("AQUI ESTOY 152");
                                    x1=posicionesX[j+1];
                                    y1=(posicionesY[j+1]);
                                    ficha2.setLocation(x1, y1);
                                     j++;
                                     System.out.println(ficha2.getX()+"--"+ficha2.getY());
                                      break;
                             }
                            }
                             else{
                                   if(ficha1.getY()<=(posX5[i]+20) && ficha1.getY()>=(posX5[i]-20)){
                                    System.out.println("AQUI ESTOY 16");
                                    x1=(posicionesX[j+1]+15);
                                    y1=posicionesY[j+1];
                                    ficha2.setLocation(x1, y1);
                                     j++;
                                     System.out.println(ficha2.getX()+"--"+ficha2.getY());
                                    break;
                                }else{
                                    System.out.println("AQUI ESTOY 17");
                                    x1=posicionesX[j+1];
                                    y1=(posicionesY[j+1]);
                                    ficha2.setLocation(x1, y1);
                                     j++;
                                     System.out.println(ficha2.getX()+"--"+ficha2.getY());
                                    break;

                             }
                                  
                             }
                               
                          }
                        }

                       break; 
            } 
               } 
                 }}
               break;
           }
    }
       }

  

    private void lanzarDados(int jugador) {
        dado11=(int)(Math.random()*6)+1;
      dado21=(int)(Math.random()*6)+1;
      
      switch(dado11){
          case 1:{
                   String path = "/imagenes/dado1.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado1.setIcon(icon);  
                   break;
          }
          case 2:{
                    String path = "/imagenes/dado2.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado1.setIcon(icon); 
                   break;
          }
          case 3:{
                    String path = "/imagenes/dado3.jpg";   
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado1.setIcon(icon);
                   break;
          }
          case 4:{
                    String path = "/imagenes/dado4.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado1.setIcon(icon); 
                   break;
          }
          case 5:{
                    String path = "/imagenes/dado5.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado1.setIcon(icon); 
                   break;
          }
          case 6:{
                    String path = "/imagenes/dado6.jpg";   
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado1.setIcon(icon); 
                   break;
          }
      }
       switch(dado21){
          case 1:{
                    String path = "/imagenes/dado1.jpg";   
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado2.setIcon(icon);  
                   break;
          }
          case 2:{
                   String path = "/imagenes/dado2.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado2.setIcon(icon); 
                   break;
          }
          case 3:{
                    String path = "/imagenes/dado3.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado2.setIcon(icon);
                   break;
          }
          case 4:{
                    String path = "/imagenes/dado4.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado2.setIcon(icon); 
                   break;
          }
          case 5:{
                    String path = "/imagenes/dado5.jpg";   
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado2.setIcon(icon); 
                   break;
          }
          case 6:{
                    String path = "/imagenes/dado6.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado2.setIcon(icon); 
                   break;
          }
      }
       
       movimientos(dado11,dado21,jugador);
    }
}
