/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parques;

import java.awt.Color;

import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;

/**
 *
 * @author johan
 */
public class Parques1 extends javax.swing.JPanel{
 int recorrido=0;
 int jugador=1;
 
 int x=90,y=90,x1=90,y1=110,turno=1;
 int mover2=0;
 int dado11,dado21,bandera=0,bandera2=0,bandera3=0,bandera4=0;
 
 Contador hilo1,hilo2,hilo3,hilo4,hilo5,hilo6,hilo7,hilo8,hilo9,hilo10,hilo11,hilo12,hilo13,hilo14,hilo15,hilo16,hilo17,hilo18,hilo19,hilo20,hilo21,hilo22;
 
 int [] posX7={250,120,430,560};
 int [] posY7={130,440,560,250};
 int [] posX5={120,10,250,330,560,670,440,340};
 int [] posY5={250,350,560,670,430,340,110,0};
 int []posicionesX={250,120,10,120,250,330,440,560,680,560,430,340};
 int []auxiliar2={250,120,10,120,250,330,440,560,680,560,430,340};
 int []posicionesY={110,240,350,430,550,670,560,420,330,250,110,0};
 int []auxiliar1={110,240,350,430,550,670,560,420,330,250,110,0};
 int [] posicionSX={0,240,550,440,260};
  int [] posicionSY={0,120,240,560,560};
 
         

    /**
     * Creates new form Parques1
     */
    public Parques1() {
        initComponents();
        
        
                         
    }
    public void paint(Graphics sd){
        super.paint(sd);
      
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ficha2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jugadoren = new javax.swing.JLabel();
        ficha4 = new javax.swing.JButton();
        ficha3 = new javax.swing.JButton();
        ficha1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lanzar = new javax.swing.JButton();
        dado1 = new javax.swing.JLabel();
        dado2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        ficha2.setBackground(new java.awt.Color(0, 0, 153));
        ficha2.setForeground(new java.awt.Color(0, 0, 153));
        ficha2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ficha2.jpg"))); // NOI18N
        ficha2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ficha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha2ActionPerformed(evt);
            }
        });
        add(ficha2);
        ficha2.setBounds(150, 50, 20, 20);

        jLabel6.setFont(new java.awt.Font("Jokerman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("1");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 51)));
        add(jLabel6);
        jLabel6.setBounds(900, 300, 20, 30);

        jugadoren.setFont(new java.awt.Font("Jokerman", 1, 14)); // NOI18N
        jugadoren.setForeground(new java.awt.Color(255, 255, 255));
        jugadoren.setText("JUGADOR EN JUEGO");
        add(jugadoren);
        jugadoren.setBounds(720, 310, 200, 22);

        ficha4.setBackground(new java.awt.Color(51, 204, 0));
        ficha4.setForeground(new java.awt.Color(51, 255, 0));
        ficha4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ficha3.jpg"))); // NOI18N
        ficha4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        ficha4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha4ActionPerformed(evt);
            }
        });
        add(ficha4);
        ficha4.setBounds(560, 120, 20, 20);

        ficha3.setBackground(new java.awt.Color(0, 204, 0));
        ficha3.setForeground(new java.awt.Color(0, 204, 0));
        ficha3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ficha3.jpg"))); // NOI18N
        ficha3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        ficha3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha3ActionPerformed(evt);
            }
        });
        add(ficha3);
        ficha3.setBounds(560, 80, 20, 19);

        ficha1.setBackground(new java.awt.Color(0, 0, 153));
        ficha1.setForeground(new java.awt.Color(0, 0, 153));
        ficha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ficha2.jpg"))); // NOI18N
        ficha1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ficha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha1ActionPerformed(evt);
            }
        });
        add(ficha1);
        ficha1.setBounds(150, 90, 20, 20);

        jLabel5.setText("jLabel5");
        add(jLabel5);
        jLabel5.setBounds(260, 560, 10, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/parque12121.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 710, 690);

        lanzar.setBackground(new java.awt.Color(0, 102, 102));
        lanzar.setForeground(new java.awt.Color(255, 255, 255));
        lanzar.setText("LANZAR");
        add(lanzar);
        lanzar.setBounds(770, 130, 100, 30);

        dado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dado-imagen-animada-0063.gif"))); // NOI18N
        add(dado1);
        dado1.setBounds(730, 200, 90, 90);

        dado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dado-imagen-animada-0063.gif"))); // NOI18N
        dado2.setText("jLabel6");
        add(dado2);
        dado2.setBounds(840, 200, 80, 80);

        jLabel4.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DE DADOS");
        add(jLabel4);
        jLabel4.setBounds(770, 70, 160, 50);

        jLabel3.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LANZAMIENTO");
        add(jLabel3);
        jLabel3.setBounds(750, 30, 160, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(-45, -3, 1050, 790);
    }// </editor-fold>//GEN-END:initComponents

    private void ficha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha2ActionPerformed
        ficha1.setEnabled(false);
        System.out.println("SELECCIONO FICHA 2 -SDFGGFG----"+mover2);    
              if(mover2==7){
                   System.out.println("SELECCIONO FICHA 2 -----"+mover2);   
                           if(hilo3!=null){
                               hilo3 = new Contador(ficha2,7,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);
                                hilo3.start();  
                            }else{
                               
                                hilo3 = new Contador(ficha2,7,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);
                                hilo3.start();   
                                }
                                
                                
                }
            if(mover2==5){
                if(hilo4!=null){
                     System.out.println("SELECCIONO FICHA 2 ER-----"+mover2);   
                             hilo4= new Contador(ficha2,5,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);
                             hilo4.start();
                            }else{
                            
                                hilo4= new Contador(ficha2,5,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);
                                hilo4.start();        
                               
                           }
             }
            if(mover2==12)  {
                    if(hilo21!=null){
                         System.out.println("SELECCIONO FICHA 2 QWERT-----"+mover2);   
                             hilo21= new Contador(ficha2,12,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);
                                hilo21.start();
                            }else{
                                System.out.println("SELECCIONO FnbvftyujnbvgftyICHA 2 QWERT-----"+mover2);   
                                hilo21= new Contador(ficha2,12,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);
                                hilo21.start();
                 
                           }
         }
             if(mover2==10)  {
                    if(hilo20!=null){
                             hilo20= new Contador(ficha2,10,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);
                                hilo20.start();
                            }else{
                            
                                hilo20= new Contador(ficha2,10,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);
                                hilo20.start();
                 
                           }
         }
    }//GEN-LAST:event_ficha2ActionPerformed

    private void ficha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha1ActionPerformed
          
              ficha2.setEnabled(false);
              System.out.println("SELECCIONO FICHA 1 -----"+mover2);    
              if(mover2==7){
                           if(hilo5!=null){
                               hilo5 = new Contador(ficha1,7,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                                hilo5.start();
                            }else{
                               
                                hilo5 = new Contador(ficha1,7,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                                hilo5.start();   
                                }
                                
                                
                }
            if(mover2==5){
                    if(hilo7!=null){
                             hilo7= new Contador(ficha1,5,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                                hilo7.start();
                            }else{
                            
                                hilo7= new Contador(ficha1,5,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                                hilo7.start();      
                               
                           }
      }
         if(mover2==12)  {
                    if(hilo20!=null){
                             hilo20= new Contador(ficha1,12,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                                hilo20.start();
                            }else{
                            
                                hilo20= new Contador(ficha1,12,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                                hilo20.start();
                 
                           }
         }
          if(mover2==10)  {
                    if(hilo20!=null){
                             hilo20= new Contador(ficha1,10,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                                hilo20.start();
                            }else{
                            
                                hilo20= new Contador(ficha1,10,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                                hilo20.start();
                 
                           }
         }
    }//GEN-LAST:event_ficha1ActionPerformed

    private void ficha3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha3ActionPerformed
        ficha4.setEnabled(false); 
        System.out.println("SELECCIONO FICHA 3 -----"+mover2);    
           if(mover2==7){
                       System.out.println("SELECCIONO FasdfgrfhyjuklICHA 3 -----"+mover2);    
            if(hilo11!=null){
                hilo11= new Contador(ficha3,7,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                hilo11.start();
            }else{

                hilo11= new Contador(ficha3,7,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                hilo11.start();

            }
        }
        if(mover2==5){
                System.out.println("SELECCIONOfdfddfdf FasdfgrfhyjuklICHA 3 -----"+mover2);    
            if(hilo13!=null){
                hilo13= new Contador(ficha3,5,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                hilo13.start();
            }else{

                hilo13= new Contador(ficha3,5,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                hilo13.start();

            }
        }
        if(mover2==12)  {
                System.out.println("SELECCIONO edgrthyuilkuyjtFasdfgrfhyjuklICHA 3 -----"+mover2);    
                    if(hilo7!=null){
                             hilo7= new Contador(ficha3,12,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                                hilo7.start();
                            }else{
                            
                                hilo7= new  Contador(ficha3,12,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                                hilo7.start();
                 
                           }
         }
         if(mover2==10)  {
                    if(hilo20!=null){
                             hilo20= new Contador(ficha3,10,ficha3.getX(),ficha3.getY(),ficha4,1,ficha1,ficha2);
                                hilo20.start();
                            }else{
                            
                                hilo20= new Contador(ficha3,10,ficha3.getX(),ficha3.getY(),ficha4,1,ficha1,ficha2);
                                hilo20.start();
                 
                           }
         }
    }//GEN-LAST:event_ficha3ActionPerformed

    private void ficha4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha4ActionPerformed
        ficha3.setEnabled(false); 
        System.out.println("SELECCIONO FICHA 4 -----"+mover2);    
            if(mover2==7){
                   System.out.println("SELertyuiytreCHA 3 -----"+mover2);    
            if(hilo9!=null){
                hilo9= new Contador(ficha4,7,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);
                hilo9.start();
            }else{

                hilo9= new Contador(ficha4,7,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);
                hilo9.start();

            }
        }
        if(mover2==5){
            System.out.println("dsfgrfhyjuklICHA 3 -----"+mover2);    
            if(hilo10!=null){
                hilo10= new Contador(ficha4,5,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);
                hilo10.start();
            }else{

                hilo10= new Contador(ficha4,5,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);
                hilo10.start();

            }
        } 
        if(mover2==12)  {
            System.out.println("ertyjuklICHA 3 -----"+mover2);    
                    if(hilo22!=null){
                             hilo22= new Contador(ficha4,12,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);
                                hilo22.start();
                            }else{
                            
                                hilo22= new Contador(ficha4,12,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);
                                hilo22.start();
                 
                           }
         }
         if(mover2==10)  {
                    if(hilo20!=null){
                             hilo20= new Contador(ficha4,10,ficha4.getX(),ficha4.getY(),ficha3,1,ficha1,ficha2);
                                hilo20.start();
                            }else{
                            
                                hilo20= new Contador(ficha4,10,ficha4.getX(),ficha4.getY(),ficha3,1,ficha1,ficha2);
                                hilo20.start();
                 
                           }
         }
    }//GEN-LAST:event_ficha4ActionPerformed

public void turnos(){
 
    if(turno==1){
   
   lanzar.addActionListener(new ActionListener() {
                        @Override
  public void actionPerformed(ActionEvent e) {
      System.out.println("LANZAR 1");
	
        lanzarDados(turno);
			}
		}
		);}
   if(turno==2){
               
       lanzar.addActionListener(new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
             
                System.out.println("LANZAR 2");
                lanzarDados(turno);
           }
           
       });
   }

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dado1;
    private javax.swing.JLabel dado2;
    private javax.swing.JButton ficha1;
    private javax.swing.JButton ficha2;
    private javax.swing.JButton ficha3;
    private javax.swing.JButton ficha4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jugadoren;
    private javax.swing.JButton lanzar;
    // End of variables declaration//GEN-END:variables

    
    
    private void lanzarDados(int jugador) {
        dado11=(int)(Math.random()*6)+1;
      dado21=(int)(Math.random()*6)+1;
      
      switch(dado11){
          case 1:{
                   String path = "/imagenes/dado1.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado1.setIcon(icon);  
                   break;
          }
          case 2:{
                    String path = "/imagenes/dado2.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado1.setIcon(icon); 
                   break;
          }
          case 3:{
                    String path = "/imagenes/dado3.jpg";   
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado1.setIcon(icon);
                   break;
          }
          case 4:{
                    String path = "/imagenes/dado4.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado1.setIcon(icon); 
                   break;
          }
          case 5:{
                    String path = "/imagenes/dado5.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado1.setIcon(icon); 
                   break;
          }
          case 6:{
                    String path = "/imagenes/dado6.jpg";   
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado1.setIcon(icon); 
                   break;
          }
      }
       switch(dado21){
          case 1:{
                    String path = "/imagenes/dado1.jpg";   
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado2.setIcon(icon);  
                   break;
          }
          case 2:{
                   String path = "/imagenes/dado2.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado2.setIcon(icon); 
                   break;
          }
          case 3:{
                    String path = "/imagenes/dado3.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado2.setIcon(icon);
                   break;
          }
          case 4:{
                    String path = "/imagenes/dado4.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado2.setIcon(icon); 
                   break;
          }
          case 5:{
                    String path = "/imagenes/dado5.jpg";   
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado2.setIcon(icon); 
                   break;
          }
          case 6:{
                    String path = "/imagenes/dado6.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado2.setIcon(icon); 
                   break;
          }
      }
       if(jugador==1){
            movimientos(dado11,dado21,jugador);
       }
       if(jugador==2){
            movimientosj2(dado11,dado21,jugador);
       }
    }
    
    private void movimientos(int dado1,int dado2,int jugador) {
        System.out.println("JUGADOR1");
        ficha3.setEnabled(false);
        ficha4.setEnabled(false);
        ficha1.setEnabled(true);
        ficha2.setEnabled(true);
        int movimientos=0;
        int movficha1=0,movficha2=0,movficha3=0,movficha4=0;
        turno=2;
        
        System.out.println("X F1"+ficha1.getX()+"Y F1"+ficha1.getY());
        System.out.println("X F2"+ficha2.getX()+"Y F2"+ficha2.getY());
        if(bandera2==0){
            turno=1;
        if(((ficha1.getX()>5&&ficha1.getX()<205)&&(ficha1.getY()>5&&ficha1.getY()<205))&&((ficha2.getX()>5&&ficha2.getX()<205)&&(ficha2.getY()>5&&ficha2.getY()<205)) ){
                bandera++;
                System.out.println("    TURNOS"+bandera);
                if(dado1==dado2 ){
                    bandera2++;
                
                    System.out.println("AQUI ESTOY CUANDCVCVO ES PAR");
                    if(hilo1!=null){
                          hilo2 = new Contador(ficha1,1,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                           hilo2.start();

                        }else{
                           hilo1 = new Contador(ficha1,1,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                           hilo1.start();
                   }
                   if(hilo2!=null){
                         hilo2 = new Contador(ficha2,1,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);
                            hilo2.start();
                        }else{
                            hilo2 = new Contador(ficha2,1,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);
                            hilo2.start();
                       }
            }   
        }
        
       if(bandera<=3){
         System.out.println("ESTOY AQUI AUN CVCVESPERANDO");
         turno=1;
       }else{
           System.out.println("Entre aqui nos  eporqudsdsdsde?");
           bandera=0;
           turno=2;
           if(turno==2){
             JOptionPane.showMessageDialog(this, "Turno del jugador 2", "Error", JOptionPane.ERROR_MESSAGE);
           }
           }
           System.out.println("El turno de aqui quedo en"+turno);
        }else{   
              System.out.println("Entre aqui nos  eporque?");
           turno=2;
            if((dado1+dado2)==7){
            turno=1;
            movimientos=0;
            movficha1=0;
            movficha2=0;
            for(int i=0;i<posX7.length;i++){
                   //System.out.println("ENTRO AQUI 1"+posX7[i]+"--"+ficha1.getX()+ficha2.getX()+"--"+ficha1.getY()+"--"+ficha2.getY());
                if((ficha1.getX()<=(posX7[i]+20) && ficha1.getX()>=(posX7[i]-20)) && (ficha1.getY()<=(posY7[i]+20) && ficha1.getY()>=(posY7[i]-20))  ){
                    movficha1++;
                    movimientos++;
                 }
                 if((ficha2.getX()<=(posX7[i]+20)&&ficha2.getX()>=(posX7[i]-20)) && (ficha2.getY()<=(posY7[i]+20) && ficha2.getY()>=(posY7[i]-20))  ){
                        movficha2++;
                        movimientos++;
                   
                }
            }
              if(movimientos>=2){
                    mover2=7;
                    System.out.println("ENTRO AQUI CUANDO ESTAN EN LA MISMA POSICION");                 
                    JOptionPane.showMessageDialog(this, "Seleccione la ficha a mover", "Error", JOptionPane.ERROR_MESSAGE);
                
              }else{
                  if(movficha1==1){
                       System.out.println("MOVER LA FICHA 1 ----++++++ 7");  
                      if(hilo5!=null){
                              hilo5 = new Contador(ficha1,7,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                                hilo5.start();
                            }else{
                             
                                hilo5 = new Contador(ficha1,7,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                                hilo5.start();
                            
                                }
                                
                                
                           }
                  else{
                      if(movficha2==1){
                          System.out.println("MOVER LA FICHA 22 ----++++++ 7");  
                          if(hilo6!=null){
                               hilo6= new Contador(ficha2,7,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);
                               hilo6.start();
                            }else{
                             
                                        hilo6= new Contador(ficha2,7,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);
                                        hilo6.start();
                                
                                
                               
                           }
                      }
                  }
              }  }        
        if((dado1+dado2)==5 || dado1==5 || dado2==5){
            movficha1=0;
            movficha2=0;
            movimientos=0;
            turno=1;
            for(int i=0;i<posX5.length;i++){
                 //  System.out.println("ENTRO AQUI 1"+posX5[i]+"--"+ficha1.getX()+ficha2.getX()+"--"+ficha1.getY()+"--"+ficha2.getY());
                if((ficha1.getX()<=(posX5[i]+20) && ficha1.getX()>=(posX5[i]-20)) && (ficha1.getY()<=(posY5[i]+20) && ficha1.getY()>=(posY5[i]-20))  ){
                     System.out.println("AQUI ESTOY 151111");
                        movficha1++;
                        movimientos++;
                 }
                 if((ficha2.getX()<=(posX5[i]+20)&&ficha2.getX()>=(posX5[i]-20)) && (ficha2.getY()<=(posY5[i]+20) && ficha2.getY()>=(posY5[i]-20))  ){
                         System.out.println("AQUI ESTOY 161111");
                        movficha2++;
                        movimientos++;
                   
                }
            }
              if(movimientos>=2){
                    mover2=5;
                     System.out.println("AQUI ESTOY 171111 "+movimientos);
                    ficha1.setEnabled(true);
                     ficha2.setEnabled(true); 
                    JOptionPane.showMessageDialog(this, "Seleccione la ficha a mover", "Error", JOptionPane.ERROR_MESSAGE);
                    
              }else{
                  if(movficha1==1){
                       System.out.println("AQUI ESTOY 181111 " +movficha1);
                      if(hilo7!=null){
                                hilo7= new Contador(ficha1,5,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                                hilo7.start();
                            }else{
                                
                                hilo7= new Contador(ficha1,5,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                                hilo7.start();
    
                           }
                  }else{
                      if(movficha2==1){
                           System.out.println("AQUI ESTOY 191111 "+movficha2);
                         if(hilo8!=null){
                                hilo8= new Contador(ficha2,5,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);                                 
                                hilo8.start();
                            }else{
                           
                                    hilo8= new Contador(ficha2,5,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);                                
                                    hilo8.start();
            
                           }
                      }
                  }
              }}
        if((dado1+dado2)==12){
            movficha1=0;
            movficha2=0;
            movimientos=0;
            turno=1;
        
             for(int i=0;i<11;i++){
                    if((ficha1.getX()<=(posicionesX[1]+20) && ficha1.getX()>=(posicionesX[1]+20)) && (ficha1.getY()<=(posicionesY[1]+20) && ficha1.getY()>=(posicionesY[1]+20))  ){
                     movficha1++;
                     movimientos++;
                    }
                     if((ficha1.getX()<=(posicionesX[4]+20) && ficha1.getX()>=(posicionesX[4]+20)) && (ficha1.getY()<=(posicionesY[4]+20) && ficha1.getY()>=(posicionesY[4]+20))  ){
                      movficha1++;
                      movimientos++; 
                    }
                    if((ficha1.getX()<=(posicionesX[7]+20) && ficha1.getX()>=(posicionesX[7]+20)) && (ficha1.getY()<=(posicionesY[7]+20) && ficha1.getY()>=(posicionesY[7]+20))  ){
                        movficha1++;
                         movimientos++;
                    }
                     if((ficha1.getX()<=(posicionesX[10]+20) && ficha1.getX()>=(posicionesX[10]+20)) && (ficha1.getY()<=(posicionesY[10]+20) && ficha1.getY()>=(posicionesY[10]+20))  ){
                       movficha1++;
                       movimientos++; 
                    }
                     if((ficha2.getX()<=(posicionesX[1]+20) && ficha2.getX()>=(posicionesX[1]+20)) && (ficha2.getY()<=(posicionesY[1]+20) && ficha2.getY()>=(posicionesY[1]+20))  ){
                     movficha2++;
                     movimientos++;
                    }
                     if((ficha2.getX()<=(posicionesX[4]+20) && ficha2.getX()>=(posicionesX[4]+20)) && (ficha2.getY()<=(posicionesY[4]+20) && ficha2.getY()>=(posicionesY[4]+20))  ){
                      movficha2++;
                      movimientos++; 
                    }
                    if((ficha2.getX()<=(posicionesX[7]+20) && ficha2.getX()>=(posicionesX[7]+20)) && (ficha2.getY()<=(posicionesY[7]+20) && ficha2.getY()>=(posicionesY[7]+20))  ){
                        movficha2++;
                         movimientos++;
                    }
                     if((ficha2.getX()<=(posicionesX[10]+20) && ficha2.getX()>=(posicionesX[10]+20)) && (ficha2.getY()<=(posicionesY[10]+20) && ficha2.getY()>=(posicionesY[10]+20))  ){
                       movficha2++;
                       movimientos++; 
                    }
             }
                     if(movimientos==0){
                         mover2=12;
                         System.out.println("AQUI ESTOY 191111111 "+movficha2);
                         JOptionPane.showMessageDialog(this, "Seleccione la ficha a mover", "Error", JOptionPane.ERROR_MESSAGE);
                    
                     }else{
                         if(movficha1==0){
                             System.out.println("AQUI ESTOY IICHA 1191111111 "+movficha2);
                             if(hilo17!=null){
                                hilo17= new Contador(ficha1,12,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                                hilo17.start();
                            }else{
                                
                                hilo17= new Contador(ficha1,12,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                                hilo17.start();
    
                           }
                         }else{
                             if(movficha2==0){
                              System.out.println("AQUI ESTOY IICHA 2222191111111 "+movficha2);
                              if(hilo18!=null){
                                    hilo18= new Contador(ficha2,12,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);                                 
                                    hilo18.start();
                                    }else{

                                        hilo18= new Contador(ficha2,12,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);                                  
                                        hilo18.start();
            
                           }
                             }
                         }
                     }
                     
             }
        
        if((dado1==5 && dado2==5) ||(dado1+dado2==10)){
            movficha1=0;
            movficha2=0;
            movimientos=0;
            turno=1;
        
             for(int i=0;i<posX5.length;i++){
                 
                    
                   if((ficha1.getX()<=(posX5[0]+20) && ficha1.getX()>=(posX5[0]+20)) && (ficha1.getY()<=(posY5[0]+20) && ficha1.getY()>=(posY5[0]+20))  ){
                            movficha1++;
                            movimientos++; 
                    }
                    if((ficha1.getX()<=(posX5[2]+20) && ficha1.getX()>=(posX5[2]+20)) && (ficha1.getY()<=(posY5[2]+20) && ficha1.getY()>=(posY5[2]+20))  ){
                            movficha1++;
                             movimientos++;
                    }
                     if((ficha1.getX()<=(posX5[4]+20) && ficha1.getX()>=(posX5[4]+20)) && (ficha1.getY()<=(posY5[4]+20) && ficha1.getY()>=(posY5[4]+20))  ){
                            movficha1++;
                            movimientos++; 
                    }
                    if((ficha1.getX()<=(posX5[6]+20) && ficha1.getX()>=(posX5[6]+20)) && (ficha1.getY()<=(posY5[6]+20) && ficha1.getY()>=(posY5[6]+20))  ){
                            movficha1++;
                            movimientos++; 
                    }
                      if((ficha2.getX()<=(posX5[0]+20) && ficha2.getX()>=(posX5[0]+20)) && (ficha2.getY()<=(posY5[0]+20) && ficha2.getY()>=(posY5[0]+20))  ){
                            movficha2++;
                            movimientos++;
                    }
                      if((ficha2.getX()<=(posX5[2]+20) && ficha2.getX()>=(posX5[2]+20)) && (ficha2.getY()<=(posY5[2]+20) && ficha2.getY()>=(posY5[2]+20))){
                            movficha1++;
                            movimientos++; 
                    }
                     if((ficha2.getX()<=(posX5[4]+20) && ficha2.getX()>=(posX5[4]+20)) && (ficha2.getY()<=(posY5[4]+20) && ficha2.getY()>=(posY5[4]+20))  ){
                            movficha1++;
                             movimientos++;
                    }
                    if((ficha2.getX()<=(posX5[6]+20) && ficha2.getX()>=(posX5[6]+20)) && (ficha2.getY()<=(posY5[6]+20) && ficha1.getY()>=(posY5[6]+20))  ){
                        movficha1++;
                        movimientos++; 
                    }

        }
             if(movimientos>=2){
                    mover2=10;
                     System.out.println("AQUI ESTOY 171111 "+movimientos);
                    ficha1.setEnabled(true);
                     ficha2.setEnabled(true); 
                    JOptionPane.showMessageDialog(this, "Seleccione la ficha a mover", "Error", JOptionPane.ERROR_MESSAGE);
                   
              }else{
                  if(movficha1==1){
                       System.out.println("AQUI ESTOY 181111 " +movficha1);
                      if(hilo7!=null){
                                hilo7= new Contador(ficha1,10,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                                hilo7.start();
                            }else{
                                
                                hilo7= new Contador(ficha1,10,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                                hilo7.start();
    
                           }
                  }else{
                      if(movficha2==1){
                           System.out.println("AQUI ESTOY 191111 "+movficha2);
                         if(hilo8!=null){
                                hilo8= new Contador(ficha2,10,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);                                
                                hilo8.start();
                            }else{
                           
                                    hilo8= new Contador(ficha2,10,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);                                 
                                    hilo8.start();
            
                           }
                      }
                  }
        
             }
        }
      
            
                 
        
        if(turno==2){
             JOptionPane.showMessageDialog(this, "Turno del jugador 2", "Error", JOptionPane.ERROR_MESSAGE);
        }     
        
        } 
       System.out.println("EL turno quedo en "+ turno);
    }
        
       
        


    private void movimientosj2(int dado1, int dado2, int jugador) {
         System.out.println("JUGADOR2");
         turno=1;
        int movimientos=0;
        int movficha1=0,movficha2=0;
        ficha1.setEnabled(false);
        ficha2.setEnabled(false);
        ficha3.setEnabled(true);
        ficha4.setEnabled(true);
        if(bandera4==0){
            turno=1;
            turno=1;
         if(((ficha3.getX()>430 &&ficha3.getX()<660)&&(ficha3.getY()>5&&ficha3.getY()<205)&&(ficha4.getX()>430 &&ficha4.getX()<660)&&(ficha4.getY()>5 && ficha4.getY()<205))){
             bandera3++;
             if(dado1==dado2){
                 turno=2;
                 bandera4++;
                  System.out.println("AQUI ESTOY CUANDO ES PAR----2");                
                    System.out.println("JUGADOR 2");
                
                        System.out.println("AQUI ESTOY CUANDO ES PAR");
                         if(hilo15!=null){
                            hilo15.reset();

                             }else{
                            hilo15 = new Contador(ficha3,1,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                            hilo15.start();
                           }
                           if(hilo16!=null){
                               hilo16.reset();
                            }else{
                                hilo16 = new Contador(ficha4,1,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);
                                hilo16.start();
                           }                     
                         }
         }
                if(bandera3<=3){
                  System.out.println("ESTOY AQUI AUN CVCVESPERANDO");
                  turno=2;
                }else{
                    System.out.println("Entre aqui nos  eporqudsdsdsde?");
                    bandera3=0;
                    turno=1;
                    if(turno==1){
                      JOptionPane.showMessageDialog(this, "Turno del jugador 1", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    }
                    System.out.println("El turno de aqui quedo en"+turno);
        }else{  
                    if((dado1+dado2)==7){
                       movimientos=0;
                       movficha1=0;
                       movficha2=0;
                       turno=2;
                       for(int i=0;i<posX7.length;i++){
                              //System.out.println("ENTRO AQUI 1"+posX7[i]+"--"+ficha1.getX()+ficha2.getX()+"--"+ficha1.getY()+"--"+ficha2.getY());
                           if((ficha3.getX()<=(posX7[i]+20) && ficha3.getX()>=(posX7[i]-20)) && (ficha3.getY()<=(posY7[i]+20) && ficha3.getY()>=(posY7[i]-20))  ){
                               movficha1++;
                               movimientos++;
                            }
                            if((ficha4.getX()<=(posX7[i]+20)&&ficha4.getX()>=(posX7[i]-20)) && (ficha4.getY()<=(posY7[i]+20) && ficha4.getY()>=(posY7[i]-20))  ){
                                   movficha2++;
                                   movimientos++;

                           }
                       }
                         if(movimientos>=2){

                               mover2=7;
                               System.out.println("ENTRO AQUI CUANDO ESTAN EN LA MISMA POSICION");
                               JOptionPane.showMessageDialog(this, "Seleccione la ficha a mover", "Error", JOptionPane.ERROR_MESSAGE);
                              
                         }else{
                             if(movficha1==1){
                                 System.out.println("MOVER LA FICHA 1 ---- 7");  
                                 if(hilo11!=null){
                                          hilo12 = new Contador(ficha3,7,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                                           hilo12.start();
                                       }else{
                                           hilo11 = new Contador(ficha3,7,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                                           hilo11.start();
                                      }

                                      }
                             else{
                                 if(movficha2==1){
                                   System.out.println("MOVER LA FICHA 2 --- 7");  

                                     if(hilo12!=null){
                                          hilo12 = new Contador(ficha4,7,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);
                                          hilo12.start();
                                       }else{
                                                hilo12 = new Contador(ficha4,7,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);
                                                hilo12.start();

                                           }

                                      }

                             }
                         }


                       }
                   if((dado1+dado2)==5 || dado1==5 || dado2==5){
                       turno=2;
                       movficha1=0;
                       movficha2=0;
                       movimientos=0;
                       for(int i=0;i<posX5.length;i++){
                            //  System.out.println("ENTRO AQUI 1"+posX5[i]+"--"+ficha1.getX()+ficha2.getX()+"--"+ficha1.getY()+"--"+ficha2.getY());
                           if((ficha3.getX()<=(posX5[i]+20) && ficha3.getX()>=(posX5[i]-20)) && (ficha3.getY()<=(posY5[i]+20) && ficha3.getY()>=(posY5[i]-20))  ){
                                System.out.println("AQUI ESTOY 151111-------");
                               movficha1++;
                               movimientos++;
                            }
                            if((ficha4.getX()<=(posX5[i]+20)&&ficha4.getX()>=(posX5[i]-20)) && (ficha4.getY()<=(posY5[i]+20) && ficha4.getY()>=(posY5[i]-20))  ){
                                   System.out.println("AQUI ESTOY 161111-------");
                                   movficha2++;
                                   movimientos++;

                           }
                       }
                         if(movimientos>=2){
                               mover2=5;
                                System.out.println("AQUI ESTOY 171111 -----"+movimientos);            
                                JOptionPane.showMessageDialog(this, "Seleccione la ficha a mover", "Error", JOptionPane.ERROR_MESSAGE);
                              
                         }else{
                             if(movficha1==1){
                                  System.out.println("AQUI ESTOY 181111 ---" +movficha1);
                                 if(hilo13!=null){
                                          hilo13 = new Contador(ficha3,5,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                                          hilo13.start();
                                       }else{
                                             hilo13 = new Contador(ficha3,5,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                                             hilo13.start();


                                      }
                             }else{
                                 if(movficha2==1){
                                      System.out.println("AQUI ESTOY 191111--- "+movficha2);
                                    if(hilo14!=null){
                                          hilo14 = new Contador(ficha4,5,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);
                                         hilo14.start();
                                       }else{
                                               hilo14 = new Contador(ficha4,5,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);
                                               hilo14.start();


                                      }
                                 }
                             }
                         }	
               }
                    if((dado1+dado2)==12){
                       movficha1=0;
                       movficha2=0;
                       movimientos=0;
                       turno=2;

                        for(int i=0;i<11;i++){
                               if((ficha3.getX()<=(posX5[0]+20) && ficha3.getX()>=(posX5[0]+20)) && (ficha3.getY()<=(posY5[0]+20) && ficha3.getY()>=(posY5[0]+20))  ){
                                       movficha1++;
                                       movimientos++; 
                               }
                               if((ficha3.getX()<=(posX5[2]+20) && ficha3.getX()>=(posX5[2]+20)) && (ficha3.getY()<=(posY5[2]+20) && ficha3.getY()>=(posY5[2]+20))  ){
                                       movficha1++;
                                        movimientos++;
                               }
                                if((ficha3.getX()<=(posX5[4]+20) && ficha3.getX()>=(posX5[4]+20)) && (ficha3.getY()<=(posY5[4]+20) && ficha3.getY()>=(posY5[4]+20))  ){
                                       movficha1++;
                                       movimientos++; 
                               }
                               if((ficha3.getX()<=(posX5[6]+20) && ficha3.getX()>=(posX5[6]+20)) && (ficha3.getY()<=(posY5[6]+20) && ficha3.getY()>=(posY5[6]+20))  ){
                                       movficha1++;
                                       movimientos++; 
                               }
                                 if((ficha4.getX()<=(posX5[0]+20) && ficha4.getX()>=(posX5[0]+20)) && (ficha4.getY()<=(posY5[0]+20) && ficha4.getY()>=(posY5[0]+20))  ){
                                       movficha2++;
                                       movimientos++;
                               }
                                 if((ficha4.getX()<=(posX5[2]+20) && ficha4.getX()>=(posX5[2]+20)) && (ficha4.getY()<=(posY5[2]+20) && ficha4.getY()>=(posY5[2]+20))){
                                       movficha2++;
                                       movimientos++; 
                               }
                                if((ficha4.getX()<=(posX5[4]+20) && ficha4.getX()>=(posX5[4]+20)) && (ficha4.getY()<=(posY5[4]+20) && ficha4.getY()>=(posY5[4]+20))  ){
                                       movficha2++;
                                        movimientos++;
                               }
                               if((ficha4.getX()<=(posX5[6]+20) && ficha4.getX()>=(posX5[6]+20)) && (ficha4.getY()<=(posY5[6]+20) && ficha3.getY()>=(posY5[6]+20))  ){
                                   movficha2++;
                                   movimientos++; 
                               }
                        }
                                if(movimientos==0){
                                    mover2=12;
                                    System.out.println("AQUI ESTOY 1911WEWE11 "+movficha2);
                                    JOptionPane.showMessageDialog(this, "Seleccione la ficha a mover", "Error", JOptionPane.ERROR_MESSAGE);
                                   
                                }else{
                                    if(movficha1==0){
                                        if(hilo17!=null){
                                           hilo17= new Contador(ficha3,12,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                                           hilo17.start();
                                       }else{

                                           hilo17= new Contador(ficha3,12,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                                           hilo17.start();

                                      }
                                    }else{
                                        if(movficha2==0){
                                         if(hilo18!=null){
                                               hilo18= new Contador(ficha4,12,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);                                  
                                               hilo18.start();
                                               }else{

                                                   hilo18= new Contador(ficha4,12,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);                                  
                                                   hilo18.start();

                                      }
                                        }
                                    }
                                }


                   }

                   if((dado1==5 && dado2==5) ||(dado1+dado2==10)){
                       movficha1=0;
                       movficha2=0;
                       movimientos=0;
                       turno=1;

                        for(int i=0;i<posX5.length;i++){


                               if((ficha3.getX()<=(posX5[0]+20) && ficha3.getX()>=(posX5[0]+20)) && (ficha3.getY()<=(posY5[0]+20) && ficha3.getY()>=(posY5[0]+20))  ){
                                       movficha1++;
                                       movimientos++; 
                               }
                               if((ficha3.getX()<=(posX5[2]+20) && ficha3.getX()>=(posX5[2]+20)) && (ficha3.getY()<=(posY5[2]+20) && ficha3.getY()>=(posY5[2]+20))  ){
                                       movficha1++;
                                        movimientos++;
                               }
                                if((ficha3.getX()<=(posX5[4]+20) && ficha3.getX()>=(posX5[4]+20)) && (ficha3.getY()<=(posY5[4]+20) && ficha3.getY()>=(posY5[4]+20))  ){
                                       movficha1++;
                                       movimientos++; 
                               }
                               if((ficha3.getX()<=(posX5[6]+20) && ficha3.getX()>=(posX5[6]+20)) && (ficha3.getY()<=(posY5[6]+20) && ficha3.getY()>=(posY5[6]+20))  ){
                                       movficha1++;
                                       movimientos++; 
                               }
                                 if((ficha4.getX()<=(posX5[0]+20) && ficha4.getX()>=(posX5[0]+20)) && (ficha4.getY()<=(posY5[0]+20) && ficha4.getY()>=(posY5[0]+20))  ){
                                       movficha2++;
                                       movimientos++;
                               }
                                 if((ficha4.getX()<=(posX5[2]+20) && ficha4.getX()>=(posX5[2]+20)) && (ficha4.getY()<=(posY5[2]+20) && ficha4.getY()>=(posY5[2]+20))){
                                       movficha2++;
                                       movimientos++; 
                               }
                                if((ficha4.getX()<=(posX5[4]+20) && ficha4.getX()>=(posX5[4]+20)) && (ficha4.getY()<=(posY5[4]+20) && ficha4.getY()>=(posY5[4]+20))  ){
                                       movficha2++;
                                        movimientos++;
                               }
                               if((ficha4.getX()<=(posX5[6]+20) && ficha4.getX()>=(posX5[6]+20)) && (ficha4.getY()<=(posY5[6]+20) && ficha3.getY()>=(posY5[6]+20))  ){
                                   movficha2++;
                                   movimientos++; 
                               }
                   }
                        if(movimientos>=2){
                               mover2=10;
                                System.out.println("AQUI ESTOY 171111 "+movimientos);
                               ficha1.setEnabled(true);
                                ficha2.setEnabled(true); 
                               JOptionPane.showMessageDialog(this, "Seleccione la ficha a mover", "Error", JOptionPane.ERROR_MESSAGE);
                           
                         }else{
                             if(movficha1==1){
                                  System.out.println("AQUI ESTOY 181111 " +movficha1);
                                 if(hilo7!=null){
                                           hilo7= new Contador(ficha3,10,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                                           hilo7.start();
                                       }else{

                                           hilo7= new Contador(ficha3,10,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                                           hilo7.start();

                                      }
                             }else{
                                 if(movficha2==1){
                                      System.out.println("AQUI ESTOY 191111 "+movficha2);
                                    if(hilo8!=null){
                                           hilo8= new Contador(ficha4,10,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);                                
                                           hilo8.start();
                                       }else{

                                               hilo8= new Contador(ficha4,10,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);                                  
                                               hilo8.start();

                                      }
                                 }
                             }

                        }
                   }
                if(turno==1){
                        JOptionPane.showMessageDialog(this, "Turno del jugador 1", "Error", JOptionPane.ERROR_MESSAGE);
                   }
        }
    }
        

}
