/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parques;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author johan
 */
public class Parques1 extends javax.swing.JPanel{
 int recorrido=0;
 int jugador=1;
 
 int x=90,y=90,x1=90,y1=110,turno=1;
 int mover2=0;
 int dado11,dado21;
 
 Contador hilo1,hilo2,hilo3,hilo4,hilo5,hilo6,hilo7,hilo8,hilo9,hilo10,hilo11,hilo12,hilo13,hilo14,hilo15,hilo16;
 
 int [] posX7={250,120,430,560};
 int [] posY7={130,440,560,250};
 int [] posX5={120,10,270,330,560,670,430,350};
 int [] posY5={260,350,560,670,440,340,130,18};
 int []posicionesX={270,120,10,120,260,340,430,560,670,560,420,340};
 int []posicionesY={130,260,350,440,560,670,560,420,340,250,130,18};
 int [] posicionSX={0,240,560,440,260};
  int [] posicionSY={0,120,230,560,560};
 
         

    /**
     * Creates new form Parques1
     */
    public Parques1() {
        initComponents();
        
        
                         
    }
    public void paint(Graphics sd){
        super.paint(sd);
      
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ficha4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ficha3 = new javax.swing.JLabel();
        ficha2 = new javax.swing.JLabel();
        ficha1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lanzar = new javax.swing.JButton();
        dado1 = new javax.swing.JLabel();
        dado2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        ficha4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bola2.jpg"))); // NOI18N
        ficha4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ficha4MouseClicked(evt);
            }
        });
        add(ficha4);
        ficha4.setBounds(560, 130, 18, 16);

        jLabel5.setText("jLabel5");
        add(jLabel5);
        jLabel5.setBounds(260, 560, 10, 14);

        ficha3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bola2.jpg"))); // NOI18N
        ficha3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ficha3MouseClicked(evt);
            }
        });
        add(ficha3);
        ficha3.setBounds(560, 100, 18, 16);

        ficha2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/circulo1.png"))); // NOI18N
        ficha2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ficha2MouseClicked(evt);
            }
        });
        add(ficha2);
        ficha2.setBounds(90, 110, 40, 16);

        ficha1.setBackground(new java.awt.Color(0, 0, 102));
        ficha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/circulo1.png"))); // NOI18N
        ficha1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ficha1MouseClicked(evt);
            }
        });
        add(ficha1);
        ficha1.setBounds(90, 80, 50, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/parque12.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 700);

        lanzar.setBackground(new java.awt.Color(0, 102, 102));
        lanzar.setForeground(new java.awt.Color(255, 255, 255));
        lanzar.setText("LANZAR");
        add(lanzar);
        lanzar.setBounds(770, 130, 100, 30);

        dado1.setText("jLabel5");
        add(dado1);
        dado1.setBounds(730, 200, 70, 80);

        dado2.setText("jLabel6");
        add(dado2);
        dado2.setBounds(840, 200, 70, 80);

        jLabel4.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DE DADOS");
        add(jLabel4);
        jLabel4.setBounds(770, 70, 160, 50);

        jLabel3.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LANZAMIENTO");
        add(jLabel3);
        jLabel3.setBounds(750, 30, 160, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(-45, -3, 1050, 790);
    }// </editor-fold>//GEN-END:initComponents

public void turnos(){
   if(turno==1){
   lanzar.addActionListener(new ActionListener() {
                        @Override
			public void actionPerformed(ActionEvent e) {
                            System.out.println("LANZAR 1");
				lanzarDados(turno);
			}
		}
		);}
   if(turno==2){
       lanzar.addActionListener(new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
                System.out.println("LANZAR 2");
                lanzarDados(turno);
           }
           
       });
   }

}
    private void ficha2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ficha2MouseClicked
    
      if(mover2==7){
         if(hilo6!=null){
                               hilo6.reset();
                            }else{
                                        hilo6= new Contador(ficha2,7,ficha2.getX(),ficha2.getY(),ficha1);
                                        hilo6.start();
              
                           }
      }
      if(mover2==5){
           if(hilo8!=null){
                               hilo8.reset();
                            }else{

                                    hilo8= new Contador(ficha2,5,ficha2.getX(),ficha2.getY(),ficha1);
                                    hilo8.start();
           
                           }
      }
    }//GEN-LAST:event_ficha2MouseClicked

    private void ficha1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ficha1MouseClicked
 
     if(mover2==7){
                           if(hilo5!=null){
                               hilo5.reset();
                            }else{
                               
                                hilo5 = new Contador(ficha1,7,ficha1.getX(),ficha1.getY(),ficha2);
                                hilo5.start();   
                                }
                                
                                
      }
      if(mover2==5){
           if(hilo7!=null){
                             hilo7.reset();
                            }else{
                            
                                hilo7= new Contador(ficha1,5,ficha1.getX(),ficha1.getY(),ficha2);
                                hilo7.start();
                                
                             
                               
                               
                           }
      }
    }//GEN-LAST:event_ficha1MouseClicked

    private void ficha3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ficha3MouseClicked
        if(mover2==7){
         if(hilo11!=null){
                               hilo11.reset();
                            }else{
                             
                                        hilo11= new Contador(ficha3,7,ficha3.getX(),ficha3.getY(),ficha4);
                                        hilo11.start();
                             
                                
                               
                           }
      }
      if(mover2==5){
           if(hilo13!=null){
                               hilo13.reset();
                            }else{
                              
                                    hilo13= new Contador(ficha3,5,ficha3.getX(),ficha3.getY(),ficha4);
                                    hilo13.start();
                                 
                                
                                 
                           }
      }
    }//GEN-LAST:event_ficha3MouseClicked

    private void ficha4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ficha4MouseClicked
       
      if(mover2==7){
         if(hilo12!=null){
                               hilo12.reset();
                            }else{
                               
                                        hilo12= new Contador(ficha4,7,ficha4.getX(),ficha4.getY(),ficha3);
                                        hilo12.start();
                             
                           }
      }
      if(mover2==5){
           if(hilo14!=null){
                               hilo14.reset();
                            }else{
                               
                                    hilo14= new Contador(ficha4,5,ficha4.getX(),ficha4.getY(),ficha3);
                                    hilo14.start();
                                 
                                
                                 
                           }
      }
    }//GEN-LAST:event_ficha4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dado1;
    private javax.swing.JLabel dado2;
    private javax.swing.JLabel ficha1;
    private javax.swing.JLabel ficha2;
    private javax.swing.JLabel ficha3;
    private javax.swing.JLabel ficha4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton lanzar;
    // End of variables declaration//GEN-END:variables

    private void movimientos(int dado1,int dado2,int jugador) {
       
       int movimientos=0;
       int movficha1=0,movficha2=0;
        
       
        
  
        turno=2;
       
        if(dado1==dado2){
                turno=1;
                
                        System.out.println("AQUI ESTOY CUANDO ES PAR");
                   if(hilo1!=null){
                    hilo1.reset();

                     }else{
                    hilo1 = new Contador(ficha1,1,ficha1.getX(),ficha1.getY(),ficha2);
                    hilo1.start();
                   }
                   if(hilo2!=null){
                       hilo2.reset();
                    }else{
                        hilo2 = new Contador(ficha2,1,ficha2.getX(),ficha2.getY(),ficha1);
                        hilo2.start();
                   }
                  
                  
                
           
           
        }
        if((dado1+dado2)==7){
            turno=1;
            movimientos=0;
            movficha1=0;
            movficha2=0;
            for(int i=0;i<posX7.length;i++){
                   //System.out.println("ENTRO AQUI 1"+posX7[i]+"--"+ficha1.getX()+ficha2.getX()+"--"+ficha1.getY()+"--"+ficha2.getY());
                if((ficha1.getX()<=(posX7[i]+20) && ficha1.getX()>=(posX7[i]-20)) && (ficha1.getY()<=(posY7[i]+20) && ficha1.getY()>=(posY7[i]-20))  ){
                    movficha1++;
                    movimientos++;
                 }
                 if((ficha2.getX()<=(posX7[i]+20)&&ficha2.getX()>=(posX7[i]-20)) && (ficha2.getY()<=(posY7[i]+20) && ficha2.getY()>=(posY7[i]-20))  ){
                        movficha2++;
                        movimientos++;
                   
                }
            }
              if(movimientos>=2){
                    mover2=7;
                    System.out.println("ENTRO AQUI CUANDO ESTAN EN LA MISMA POSICION");
                   
                    JOptionPane.showMessageDialog(this, "Seleccione la ficha a mover", "Error", JOptionPane.ERROR_MESSAGE);
              }else{
                  if(movficha1==1){
                      if(hilo5!=null){
                               hilo5.reset();
                            }else{
                             
                                hilo5 = new Contador(ficha1,7,ficha1.getX(),ficha1.getY(),ficha2);
                                hilo5.start();
                            
                                }
                                
                                
                           }
                  else{
                      if(movficha2==1){
                          if(hilo6!=null){
                               hilo6.reset();
                            }else{
                             
                                        hilo6= new Contador(ficha2,7,ficha2.getX(),ficha2.getY(),ficha1);
                                        hilo6.start();
                                
                                
                               
                           }
                      }
                  }
              }
              
            
            }
        if((dado1+dado2)==5 || dado1==5 || dado2==5){
            movficha1=0;
            movficha2=0;
            movimientos=0;
            turno=1;
            for(int i=0;i<posX5.length;i++){
                 //  System.out.println("ENTRO AQUI 1"+posX5[i]+"--"+ficha1.getX()+ficha2.getX()+"--"+ficha1.getY()+"--"+ficha2.getY());
                if((ficha1.getX()<=(posX5[i]+20) && ficha1.getX()>=(posX5[i]-20)) && (ficha1.getY()<=(posY5[i]+20) && ficha1.getY()>=(posY5[i]-20))  ){
                     System.out.println("AQUI ESTOY 151111");
                    movficha1++;
                    movimientos++;
                 }
                 if((ficha2.getX()<=(posX5[i]+20)&&ficha2.getX()>=(posX5[i]-20)) && (ficha2.getY()<=(posY5[i]+20) && ficha2.getY()>=(posY5[i]-20))  ){
                         System.out.println("AQUI ESTOY 161111");
                        movficha2++;
                        movimientos++;
                   
                }
            }
              if(movimientos>=2){
                    mover2=5;
                     System.out.println("AQUI ESTOY 171111 "+movimientos);
                    ficha1.setEnabled(true);
                     ficha2.setEnabled(true); 
                    JOptionPane.showMessageDialog(this, "Seleccione la ficha a mover", "Error", JOptionPane.ERROR_MESSAGE);
              }else{
                  if(movficha1==1){
                       System.out.println("AQUI ESTOY 181111 " +movficha1);
                      if(hilo7!=null){
                               hilo7.reset();
                            }else{
                                
                                hilo7= new Contador(ficha1,5,ficha1.getX(),ficha1.getY(),ficha2);
                                hilo7.start();
    
                           }
                  }else{
                      if(movficha2==1){
                           System.out.println("AQUI ESTOY 191111 "+movficha2);
                         if(hilo8!=null){
                               hilo8.reset();
                            }else{
                           
                                    hilo8= new Contador(ficha2,5,ficha2.getX(),ficha2.getY(),ficha1);
                                    jugador=1;
                                    hilo8.start();
            
                           }
                      }
                  }
              }
        }
        if(turno==2){
             JOptionPane.showMessageDialog(this, "Turno del jugador 2", "Error", JOptionPane.ERROR_MESSAGE);
        }
       }
       

    private void lanzarDados(int jugador) {
        dado11=(int)(Math.random()*6)+1;
      dado21=(int)(Math.random()*6)+1;
      
      switch(dado11){
          case 1:{
                   String path = "/imagenes/dado1.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado1.setIcon(icon);  
                   break;
          }
          case 2:{
                    String path = "/imagenes/dado2.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado1.setIcon(icon); 
                   break;
          }
          case 3:{
                    String path = "/imagenes/dado3.jpg";   
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado1.setIcon(icon);
                   break;
          }
          case 4:{
                    String path = "/imagenes/dado4.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado1.setIcon(icon); 
                   break;
          }
          case 5:{
                    String path = "/imagenes/dado5.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado1.setIcon(icon); 
                   break;
          }
          case 6:{
                    String path = "/imagenes/dado6.jpg";   
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado1.setIcon(icon); 
                   break;
          }
      }
       switch(dado21){
          case 1:{
                    String path = "/imagenes/dado1.jpg";   
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado2.setIcon(icon);  
                   break;
          }
          case 2:{
                   String path = "/imagenes/dado2.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado2.setIcon(icon); 
                   break;
          }
          case 3:{
                    String path = "/imagenes/dado3.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado2.setIcon(icon);
                   break;
          }
          case 4:{
                    String path = "/imagenes/dado4.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado2.setIcon(icon); 
                   break;
          }
          case 5:{
                    String path = "/imagenes/dado5.jpg";   
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado2.setIcon(icon); 
                   break;
          }
          case 6:{
                    String path = "/imagenes/dado6.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado2.setIcon(icon); 
                   break;
          }
      }
       if(jugador==1){
            movimientos(dado11,dado21,jugador);
       }
       if(jugador==2){
            movimientosj2(dado11,dado21,jugador);
       }
    }

    private void movimientosj2(int dado1, int dado2, int jugador) {
        int movimientos=0;
       int movficha1=0,movficha2=0;
     
            turno=1;
             if(dado1==dado2){
                 turno=2;
            
                  System.out.println("AQUI ESTOY CUANDO ES PAR----2");                
                    System.out.println("JUGADOR 2");
                
                        System.out.println("AQUI ESTOY CUANDO ES PAR");
                         if(hilo15!=null){
                            hilo15.reset();

                             }else{
                            hilo15 = new Contador(ficha3,1,ficha3.getX(),ficha3.getY(),ficha4);
                            hilo15.start();
                           }
                           if(hilo16!=null){
                               hilo16.reset();
                            }else{
                                hilo16 = new Contador(ficha4,1,ficha4.getX(),ficha4.getY(),ficha3);
                                hilo16.start();
                           }                     
                         }

        if((dado1+dado2)==7){
            movimientos=0;
            movficha1=0;
            movficha2=0;
            turno=2;
            for(int i=0;i<posX7.length;i++){
                   //System.out.println("ENTRO AQUI 1"+posX7[i]+"--"+ficha1.getX()+ficha2.getX()+"--"+ficha1.getY()+"--"+ficha2.getY());
                if((ficha3.getX()<=(posX7[i]+20) && ficha3.getX()>=(posX7[i]-20)) && (ficha3.getY()<=(posY7[i]+20) && ficha3.getY()>=(posY7[i]-20))  ){
                    movficha1++;
                    movimientos++;
                 }
                 if((ficha4.getX()<=(posX7[i]+20)&&ficha4.getX()>=(posX7[i]-20)) && (ficha4.getY()<=(posY7[i]+20) && ficha4.getY()>=(posY7[i]-20))  ){
                        movficha2++;
                        movimientos++;
                   
                }
            }
              if(movimientos>=2){
                    mover2=7;
                    System.out.println("ENTRO AQUI CUANDO ESTAN EN LA MISMA POSICION");
                 
                    JOptionPane.showMessageDialog(this, "Seleccione la ficha a mover", "Error", JOptionPane.ERROR_MESSAGE);
              }else{
                  if(movficha1==1){
                      if(hilo11!=null){
                               hilo11.reset();
                            }else{
                                hilo11 = new Contador(ficha3,7,ficha3.getX(),ficha3.getY(),ficha4);
                           }
                
                           }
                  else{
                      if(movficha2==1){
                          if(hilo12!=null){
                               hilo12.reset();
                            }else{
                                     hilo12 = new Contador(ficha4,7,ficha4.getX(),ficha4.getY(),ficha3);
                                     hilo12.start();
                                    
                                }
                               
                           }
                      
                  }
              }
              
            
            }
        if((dado1+dado2)==5 || dado1==5 || dado2==5){
            turno=2;
            movficha1=0;
            movficha2=0;
            movimientos=0;
            for(int i=0;i<posX5.length;i++){
                 //  System.out.println("ENTRO AQUI 1"+posX5[i]+"--"+ficha1.getX()+ficha2.getX()+"--"+ficha1.getY()+"--"+ficha2.getY());
                if((ficha3.getX()<=(posX5[i]+20) && ficha3.getX()>=(posX5[i]-20)) && (ficha3.getY()<=(posY5[i]+20) && ficha3.getY()>=(posY5[i]-20))  ){
                     System.out.println("AQUI ESTOY 151111-------");
                    movficha1++;
                    movimientos++;
                 }
                 if((ficha4.getX()<=(posX5[i]+20)&&ficha4.getX()>=(posX5[i]-20)) && (ficha4.getY()<=(posY5[i]+20) && ficha4.getY()>=(posY5[i]-20))  ){
                        System.out.println("AQUI ESTOY 161111-------");
                        movficha2++;
                        movimientos++;
                   
                }
            }
              if(movimientos>=2){
                    mover2=5;
                     System.out.println("AQUI ESTOY 171111 -----"+movimientos);
               
                    JOptionPane.showMessageDialog(this, "Seleccione la ficha a mover", "Error", JOptionPane.ERROR_MESSAGE);
              }else{
                  if(movficha1==1){
                       System.out.println("AQUI ESTOY 181111 ---" +movficha1);
                      if(hilo13!=null){
                               hilo13.reset();
                            }else{
                                  hilo13 = new Contador(ficha3,5,ficha3.getX(),ficha3.getY(),ficha4);
                                  hilo13.start();
                                  
                               
                           }
                  }else{
                      if(movficha2==1){
                           System.out.println("AQUI ESTOY 191111--- "+movficha2);
                         if(hilo14!=null){
                               hilo14.reset();
                            }else{
                                    hilo14 = new Contador(ficha4,5,ficha4.getX(),ficha4.getY(),ficha3);
                                    hilo14.start();
                                    
                                
                           }
                      }
                  }
              }	
    }
     if(turno==1){
             JOptionPane.showMessageDialog(this, "Turno del jugador 1", "Error", JOptionPane.ERROR_MESSAGE);
        }
}
}
