/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parques;

import java.awt.Color;

import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;

/**
 *
 * @author johan
 */
public class Parques2 extends javax.swing.JPanel{
 int recorrido=0;
 int jugador=1;
 
 int x=90,y=90,x1=90,y1=110,turno=1;
 int mover2=0;
 int dado11,dado21,suma;
 String opciond1,opciond2;
 Contador2 hilo1,hilo2,hilo3,hilo4,hilo5,hilo6,hilo7,hilo8,hilo9,hilo10,hilo11,hilo12,hilo13,hilo14;
 

 int []posicionesX={250,120,10,120,250,330,440,560,680,560,430,340};
 int []auxiliar2={270,120,10,120,260,340,430,560,670,560,420,340};
 int []posicionesY={110,240,350,430,550,670,560,420,330,250,110,0};
 int []auxiliar1={110,260,350,440,560,670,560,420,340,260,110,0};;

 
         

    /**
     * Creates new form Parques1
     */
    public Parques2() {
        initComponents();
        
        
                         
    }
    public void paint(Graphics sd){
        super.paint(sd);
      
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        correr2 = new javax.swing.JLabel();
        ficha2 = new javax.swing.JButton();
        correr1 = new javax.swing.JLabel();
        ficha4 = new javax.swing.JButton();
        ficha3 = new javax.swing.JButton();
        ficha1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lanzar = new javax.swing.JButton();
        dado1 = new javax.swing.JLabel();
        dado2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        correr2.setFont(new java.awt.Font("Jokerman", 1, 12)); // NOI18N
        correr2.setForeground(new java.awt.Color(255, 255, 255));
        correr2.setText("FICHAS DEL JUGADOR 2");
        add(correr2);
        correr2.setBounds(730, 430, 180, 19);

        ficha2.setBackground(new java.awt.Color(0, 0, 153));
        ficha2.setForeground(new java.awt.Color(0, 0, 153));
        ficha2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ficha2.jpg"))); // NOI18N
        ficha2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ficha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha2ActionPerformed(evt);
            }
        });
        add(ficha2);
        ficha2.setBounds(110, 60, 20, 20);

        correr1.setFont(new java.awt.Font("Jokerman", 1, 12)); // NOI18N
        correr1.setForeground(new java.awt.Color(255, 255, 255));
        correr1.setText("FICHAS DEL JUGADOR 1");
        add(correr1);
        correr1.setBounds(730, 330, 210, 19);

        ficha4.setBackground(new java.awt.Color(51, 204, 0));
        ficha4.setForeground(new java.awt.Color(51, 255, 0));
        ficha4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ficha3.jpg"))); // NOI18N
        ficha4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        ficha4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha4ActionPerformed(evt);
            }
        });
        add(ficha4);
        ficha4.setBounds(560, 120, 20, 20);

        ficha3.setBackground(new java.awt.Color(0, 204, 0));
        ficha3.setForeground(new java.awt.Color(0, 204, 0));
        ficha3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ficha3.jpg"))); // NOI18N
        ficha3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        ficha3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha3ActionPerformed(evt);
            }
        });
        add(ficha3);
        ficha3.setBounds(560, 80, 20, 19);

        ficha1.setBackground(new java.awt.Color(0, 0, 153));
        ficha1.setForeground(new java.awt.Color(0, 0, 153));
        ficha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ficha2.jpg"))); // NOI18N
        ficha1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ficha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ficha1ActionPerformed(evt);
            }
        });
        add(ficha1);
        ficha1.setBounds(110, 90, 20, 20);

        jLabel5.setText("jLabel5");
        add(jLabel5);
        jLabel5.setBounds(260, 560, 10, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/parque12121.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 710, 690);

        lanzar.setBackground(new java.awt.Color(0, 102, 102));
        lanzar.setForeground(new java.awt.Color(255, 255, 255));
        lanzar.setText("LANZAR");
        add(lanzar);
        lanzar.setBounds(770, 130, 100, 30);

        dado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dado-imagen-animada-0063.gif"))); // NOI18N
        add(dado1);
        dado1.setBounds(730, 190, 90, 90);

        dado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/dado-imagen-animada-0063.gif"))); // NOI18N
        dado2.setText("jLabel6");
        add(dado2);
        dado2.setBounds(850, 190, 80, 80);

        jLabel4.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DE DADOS");
        add(jLabel4);
        jLabel4.setBounds(770, 70, 160, 50);

        jLabel3.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LANZAMIENTO");
        add(jLabel3);
        jLabel3.setBounds(750, 30, 160, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(-45, -3, 1050, 790);
    }// </editor-fold>//GEN-END:initComponents

    private void ficha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha2ActionPerformed
      opciond1=String.valueOf(dado11);
      opciond2=String.valueOf(dado21);
          suma=dado11+dado21;
        Object[] nuevo= new Object[] { opciond1, opciond2, "Todo" };
        Object[] options = null;
        String seleccion = (String) JOptionPane.showInputDialog(this, "Desea mover?",  "Selector de opciones",
        JOptionPane.QUESTION_MESSAGE, null,nuevo, "opcion 1");
        System.out.println("se"+seleccion);
        if(seleccion=="Todo"){
                System.out.println("se12swdfgh12"+seleccion);
                if(hilo11!=null){
                    hilo11 = new Contador2(ficha2,suma,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);
                    hilo11.start();

                     }else{
                        hilo11 = new Contador2(ficha2,suma,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);
                        hilo11.start();
                   }
     
        }else{
            if(seleccion==opciond1){
                    System.out.println("se1wdefgrthyjugfre212"+seleccion);
                if(hilo12!=null){
                     hilo12 = new Contador2(ficha2,suma,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);
                     hilo12.start();

                     }else{
                        hilo12 = new Contador2(ficha2,dado11,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);
                        hilo12.start();
                   }
                   if(hilo13!=null){
                       hilo13 = new Contador2(ficha1,dado21,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                        hilo13.start();
                    }else{
                        hilo13 = new Contador2(ficha1,dado21,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                        hilo13.start();
                   }
            }else{
                if(hilo3!=null){
                        System.out.println("sqwqwqwqwwqwqe1212"+seleccion);
                    hilo3 = new Contador2(ficha2,dado21,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);
                    hilo3.start();

                     }else{
                        hilo3 = new Contador2(ficha2,dado21,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);
                        hilo3.start();
                   }
                   if(hilo7!=null){
                       hilo7 = new Contador2(ficha1,dado11,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                       hilo7.start();
                    }else{
                        hilo7 = new Contador2(ficha1,dado11,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                        hilo7.start();
                   }
                
            }
        }
      

    }//GEN-LAST:event_ficha2ActionPerformed

    private void ficha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha1ActionPerformed
           opciond1=String.valueOf(dado11);
           suma=dado11+dado21;
      opciond2=String.valueOf(dado21);
        Object[] nuevo= new Object[] { opciond1, opciond2, "Todo" };
        Object[] options = null;
        String seleccion = (String) JOptionPane.showInputDialog(this, "Desea mover?",  "Selector de opciones",
        JOptionPane.QUESTION_MESSAGE, null,nuevo, "opcion 1");
        System.out.println("se"+seleccion);
        if(seleccion=="Todo"){
                 System.out.println("se1212"+seleccion);
                if(hilo4!=null){
                     hilo4 = new Contador2(ficha1,suma,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                     hilo4.start();

                     }else{
                        hilo4 = new Contador2(ficha1,suma,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                        hilo4.start();
                   }
     
        }else{
            if(seleccion==opciond1){
                 System.out.println("se1212sdsd"+seleccion);
                if(hilo3!=null){
                       hilo3 = new Contador2(ficha1,dado11,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                        hilo3.start();

                     }else{
                        hilo3 = new Contador2(ficha1,dado11,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                        hilo3.start();
                   }
                   if(hilo7!=null){
                        hilo7 = new Contador2(ficha2,dado21,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);
                        hilo7.start();
                    }else{
                        hilo7 = new Contador2(ficha2,dado21,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);
                        hilo7.start();
                   }
            }else{
                 System.out.println("se12dsds12"+seleccion);
                if(hilo3!=null){
                    hilo3 = new Contador2(ficha1,dado21,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                        hilo3.start();

                     }else{
                        hilo3 = new Contador2(ficha1,dado21,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                        hilo3.start();
                   }
                   if(hilo7!=null){
                       hilo7 = new Contador2(ficha2,dado11,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);
                        hilo7.start();
                    }else{
                        hilo7 = new Contador2(ficha2,dado11,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);
                        hilo7.start();
                   }
                
            }
        }
      
             
    }//GEN-LAST:event_ficha1ActionPerformed

    private void ficha3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha3ActionPerformed
      opciond1=String.valueOf(dado11);
      opciond2=String.valueOf(dado21);
        Object[] nuevo= new Object[] { opciond1, opciond2, "Todo" };
        Object[] options = null;
        String seleccion = (String) JOptionPane.showInputDialog(this, "Desea mover?",  "Selector de opciones",
        JOptionPane.QUESTION_MESSAGE, null,nuevo, "opcion 1");
        System.out.println("se"+seleccion);
        if(seleccion=="Todo"){
                if(hilo8!=null){
                    hilo8 = new Contador2(ficha3,suma,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                    hilo8.start();

                     }else{
                        hilo8 = new Contador2(ficha3,suma,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                        hilo8.start();
                   }
     
        }else{
            if(seleccion==opciond1){
                if(hilo9!=null){
                    hilo9 = new Contador2(ficha3,dado11,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                    hilo9.start();

                     }else{
                        hilo9 = new Contador2(ficha3,dado11,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                        hilo9.start();
                   }
                   if(hilo10!=null){
                        hilo10 = new Contador2(ficha4,dado21,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);
                        hilo10.start();
                    }else{
                        hilo10 = new Contador2(ficha4,dado21,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);
                        hilo10.start();
                   }
            }else{
                if(hilo3!=null){
                    hilo3 = new Contador2(ficha3,dado21,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                    hilo3.start();

                     }else{
                        hilo3 = new Contador2(ficha3,dado21,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                        hilo3.start();
                   }
                   if(hilo7!=null){
                       hilo7 = new Contador2(ficha4,dado11,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);
                       hilo7.start();
                    }else{
                        hilo7 = new Contador2(ficha4,dado11,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);
                        hilo7.start();
                   }
                
            }
        }
      

    }//GEN-LAST:event_ficha3ActionPerformed

    private void ficha4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ficha4ActionPerformed
       opciond1=String.valueOf(dado11);
      opciond2=String.valueOf(dado21);
        Object[] nuevo= new Object[] { opciond1, opciond2, "Todo" };
        Object[] options = null;
        String seleccion = (String) JOptionPane.showInputDialog(this, "Desea mover?",  "Selector de opciones",
        JOptionPane.QUESTION_MESSAGE, null,nuevo, "opcion 1");
        System.out.println("se"+seleccion);
        if(seleccion=="Todo"){
                if(hilo3!=null){
                    hilo3 = new Contador2(ficha4,suma,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);
                    hilo3.start();

                     }else{
                        hilo3 = new Contador2(ficha4,suma,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);
                        hilo3.start();
                   }
     
        }else{
            if(seleccion==opciond1){
                if(hilo3!=null){
                    hilo3 = new Contador2(ficha4,dado11,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);
                    hilo3.start();

                     }else{
                        hilo3 = new Contador2(ficha4,dado11,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);
                        hilo3.start();
                   }
                   if(hilo7!=null){
                        hilo7 = new Contador2(ficha3,dado21,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                        hilo7.start();
                    }else{
                        hilo7 = new Contador2(ficha3,dado21,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                        hilo7.start();
                   }
            }else{
                if(hilo3!=null){
                      hilo3 = new Contador2(ficha4,dado21,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);
                       hilo3.start();

                     }else{
                        hilo3 = new Contador2(ficha4,dado21,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);
                        hilo3.start();
                   }
                   if(hilo7!=null){
                        hilo7 = new Contador2(ficha3,dado11,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                        hilo7.start();
                    }else{
                        hilo7 = new Contador2(ficha3,dado11,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                        hilo7.start();
                   }
                
            }
        }
    }//GEN-LAST:event_ficha4ActionPerformed

public void turnos(){
   if(turno==1){
   
   lanzar.addActionListener(new ActionListener() {
                        @Override
  public void actionPerformed(ActionEvent e) {
      System.out.println("LANZAR 1");
	
        lanzarDados(turno);
			}
		}
		);}
   if(turno==2){
               
       lanzar.addActionListener(new ActionListener() {
           @Override
           public void actionPerformed(ActionEvent e) {
             
                System.out.println("LANZAR 2");
                lanzarDados(turno);
           }
           
       });
   }

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel correr1;
    private javax.swing.JLabel correr2;
    private javax.swing.JLabel dado1;
    private javax.swing.JLabel dado2;
    private javax.swing.JButton ficha1;
    private javax.swing.JButton ficha2;
    private javax.swing.JButton ficha3;
    private javax.swing.JButton ficha4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton lanzar;
    // End of variables declaration//GEN-END:variables

    
    
    private void lanzarDados(int jugador) {
        dado11=(int)(Math.random()*6)+1;
      dado21=(int)(Math.random()*6)+1;
      
      switch(dado11){
          case 1:{
                   String path = "/imagenes/dado1.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado1.setIcon(icon);  
                   break;
          }
          case 2:{
                    String path = "/imagenes/dado2.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado1.setIcon(icon); 
                   break;
          }
          case 3:{
                    String path = "/imagenes/dado3.jpg";   
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado1.setIcon(icon);
                   break;
          }
          case 4:{
                    String path = "/imagenes/dado4.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado1.setIcon(icon); 
                   break;
          }
          case 5:{
                    String path = "/imagenes/dado5.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado1.setIcon(icon); 
                   break;
          }
          case 6:{
                    String path = "/imagenes/dado6.jpg";   
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado1.setIcon(icon); 
                   break;
          }
      }
       switch(dado21){
          case 1:{
                    String path = "/imagenes/dado1.jpg";   
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado2.setIcon(icon);  
                   break;
          }
          case 2:{
                   String path = "/imagenes/dado2.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado2.setIcon(icon); 
                   break;
          }
          case 3:{
                    String path = "/imagenes/dado3.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado2.setIcon(icon);
                   break;
          }
          case 4:{
                    String path = "/imagenes/dado4.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado2.setIcon(icon); 
                   break;
          }
          case 5:{
                    String path = "/imagenes/dado5.jpg";   
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado2.setIcon(icon); 
                   break;
          }
          case 6:{
                    String path = "/imagenes/dado6.jpg";  
                   URL url = this.getClass().getResource(path);  
                   ImageIcon icon = new ImageIcon(url);  
                   dado2.setIcon(icon); 
                   break;
          }
      }
       if(jugador==1){
            movimientos(dado11,dado21,jugador);
       }
       if(jugador==2){
            movimientosj2(dado11,dado21,jugador);
       }
    }
    
    
    private void movimientos(int dado1,int dado2,int jugador) {
        ficha3.setEnabled(false);
        ficha4.setEnabled(false);
        ficha1.setEnabled(true);
        ficha2.setEnabled(true);
        suma=dado11+dado21;
       int movimientos=0;
       int movficha1=0,movficha2=0,movficha3=0,movficha4=0;
       turno=2; 
        if(dado1==dado2 ){
                turno=1;
                System.out.println("AQUI ESTOY CUANDO ES PAR");
                if(hilo1!=null){
                    hilo1.reset();

                     }else{
                        hilo1 = new Contador2(ficha1,1,ficha1.getX(),ficha1.getY(),ficha2,1,ficha3,ficha4);
                        hilo1.start();
                   }
                   if(hilo2!=null){
                       hilo2.reset();
                    }else{
                        hilo2 = new Contador2(ficha2,1,ficha2.getX(),ficha2.getY(),ficha1,1,ficha3,ficha4);
                        hilo2.start();
                   }
                  
                  
                
           
           
        }
       
                 
        
        if(turno==2){
             JOptionPane.showMessageDialog(this, "Turno del jugador 2", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }
        
       
        


    private void movimientosj2(int dado1, int dado2, int jugador) {
        int movimientos=0;
        int movficha1=0,movficha2=0;
        ficha1.setEnabled(false);
        ficha2.setEnabled(false);
        ficha3.setEnabled(true);
        ficha4.setEnabled(true);
     
            turno=1;
             if(dado1==dado2){
                 turno=2;
            
                  System.out.println("AQUI ESTOY CUANDO ES PAR----2");                
                    System.out.println("JUGADOR 2");
                
                        System.out.println("AQUI ESTOY CUANDO ES PAR");
                         if(hilo5!=null){
                            hilo5.reset();

                             }else{
                            hilo5 = new Contador2(ficha3,1,ficha3.getX(),ficha3.getY(),ficha4,2,ficha1,ficha2);
                            hilo5.start();
                           }
                           if(hilo6!=null){
                               hilo6.reset();
                            }else{
                                hilo6 = new Contador2(ficha4,1,ficha4.getX(),ficha4.getY(),ficha3,2,ficha1,ficha2);
                                hilo6.start();
                           }                     
                         }
       
       
     if(turno==1){
             JOptionPane.showMessageDialog(this, "Turno del jugador 1", "Error", JOptionPane.ERROR_MESSAGE);
        }
}

  
}
